spring:
  application:
    name: LinkDisk
  servlet:
    multipart:
      max-file-size:  50MB
      max-request-size: 50MB
server:
  port: 9000

hdfs:
  path: hdfs://101.200.36.213:9000
  username: root