spring:
  application:
    name: LinkDisk
  servlet:
    multipart:
      max-file-size:  500MB
      max-request-size: 500MB
server:
  port: 9000

hdfs:
  path: hdfs://192.168.42.177:9000
  username: root