spring:
  redis:
    database: 0
    host: 106.14.218.153
    port: 6379
    timeout: 5000ms
    pool:
      timeout: 0
    password: shark
  application:
    name: LinkDisk
  servlet:
    multipart:
      max-file-size:  500MB
      max-request-size: 500MB
  datasource:
    username: root
    url: jdbc:mysql://linkjb.com:3306/linkdisk?useUnicode=true?characterEncoding=utf8
    password: xiongge
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9000
hdfs:
  path: hdfs://192.168.42.177:9000
  username: root
mybatis:
  type-aliases-package: com.linkjb.entity
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名转换
logging:
  level:
    com.linkjb.dao : debug
  config: classpath:logback-linkdisk.xml
